# Generated by Django 3.2.5 on 2022-02-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0023_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
