# Generated by Django 3.2.5 on 2022-02-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0024_studentuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('experience', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('timing', models.CharField(max_length=100)),
                ('salary', models.FloatField(max_length=20)),
                ('desc', models.CharField(max_length=300)),
                ('creationdate', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.recruiter')),
            ],
        ),
    ]
