# Generated by Django 3.2.5 on 2022-02-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0026_auto_20220228_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addjob',
            name='timing',
        ),
    ]
