# Generated by Django 3.2.5 on 2022-03-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0027_remove_addjob_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('applydate', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.addjob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.studentuser')),
            ],
        ),
    ]
